from sqlite3 import dbapi2 as sqlite

# open database
con=sqlite.connect("puzzlebase.db")

# create tables
con.execute('create table set1(filename, id, x, y)')
con.execute('create table set2(filename, id, x, y)')
con.execute('create table set3(filename, id, x, y)')

con.commit()

# Fill tables
con.execute("insert into set1 (filename, id, x, y) values ( 'A2B6C.png', 1, 2, 6)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A1B0C.png', 2, 1, 0)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B8C.png', 3, 5, 8)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B5C.png', 4, 5, 5)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A3B7C.png', 5, 3, 7)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A9B1C.png', 8, 9, 1)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A0B8C.png', 12, 0, 8)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B1C.png', 14, 5, 1)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A7B8C.png', 16, 7, 8)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A4B0C.png', 20, 4, 0)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A8B9C.png', 21, 8, 9)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A2B3C.png', 23, 2, 3)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A0B1C.png', 25, 0, 1)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A1B8C.png', 27, 1, 8)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A9B0C.png', 29, 9, 0)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A8B4C.png', 31, 8, 4)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A2B5C.png', 33, 2, 5)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A1B1C.png', 35, 1, 1)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A7B6C.png', 37, 7, 6)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A6B3C.png', 41, 6, 3)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A7B3C.png', 43, 7, 3)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A6B2C.png', 45, 6, 2)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A6B5C.png', 49, 6, 5)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A4B3C.png', 50, 4, 3)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A4B1C.png', 52, 4, 1)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A6B1C.png', 53, 6, 1)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A8B2C.png', 56, 8, 2)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A1B5C.png', 59, 1, 5)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A7B4C.png', 61, 7, 4)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A9B5C.png', 64, 9, 5)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A2B9C.png', 65, 2, 9)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A9B4C.png', 66, 9, 4)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A0B4C.png', 68, 0, 4)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B4C.png', 69, 5, 4)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A2B8C.png', 70, 2, 8)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A9B8C.png', 71, 9, 8)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A3B4C.png', 73, 3, 4)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B0C.png', 74, 5, 0)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A6B0C.png', 75, 6, 0)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A7B9C.png', 77, 7, 9)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A9B2C.png', 78, 9, 2)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A7B2C.png', 79, 7, 2)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A1B9C.png', 80, 1, 9)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A6B6C.png', 81, 6, 6)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A6B9C.png', 82, 6, 9)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A1B6C.png', 83, 1, 6)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A6B7C.png', 85, 6, 7)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A3B0C.png', 87, 3, 0)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A4B2C.png', 90, 4, 2)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A1B2C.png', 91, 1, 2)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A1B7C.png', 93, 1, 7)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A9B3C.png', 98, 9, 3)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A8B7C.png', 100, 8, 7)")

con.execute("insert into set1 (filename, id, x, y) values ( 'A5B5D.png', 87, 3, 0)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B5D.png', 61, 7, 4)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B5D.png', 33, 2, 5)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B5D.png', 2, 1, 0)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B5D.png', 91, 1, 2)")

con.execute("insert into set1 (filename, id, x, y) values ( 'A5B5D.png', 90, 4, 2)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B5D.png', 29, 9, 0)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B5D.png', 60, 4, 4)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B5D.png', 22, 4, 9)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B5D.png', 92, 9, 9)")

con.execute("insert into set1 (filename, id, x, y) values ( 'A5B5D.png', 28, 7, 7)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B5D.png', 42, 3, 1)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B5D.png', 58, 8, 6)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B5D.png', 10, 5, 6)")
con.execute("insert into set1 (filename, id, x, y) values ( 'A5B5D.png', 95, 3, 2)")

con.execute("insert into set2 (filename, id, x, y) values ( 'A2B6C.png', 1, 2, 6)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A1B0C.png', 2, 1, 0)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B8C.png', 3, 5, 8)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B5C.png', 4, 5, 5)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A3B7C.png', 5, 3, 7)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A9B1C.png', 8, 9, 1)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A0B8C.png', 12, 0, 8)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B1C.png', 14, 5, 1)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A7B8C.png', 16, 7, 8)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A4B0C.png', 20, 4, 0)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A8B9C.png', 21, 8, 9)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A2B3C.png', 23, 2, 3)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A0B1C.png', 25, 0, 1)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A1B8C.png', 27, 1, 8)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A9B0C.png', 29, 9, 0)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A8B4C.png', 31, 8, 4)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A2B5C.png', 33, 2, 5)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A1B1C.png', 35, 1, 1)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A7B6C.png', 37, 7, 6)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A6B3C.png', 41, 6, 3)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A7B3C.png', 43, 7, 3)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A6B2C.png', 45, 6, 2)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A6B5C.png', 49, 6, 5)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A4B3C.png', 50, 4, 3)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A4B1C.png', 52, 4, 1)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A6B1C.png', 53, 6, 1)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A8B2C.png', 56, 8, 2)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A1B5C.png', 59, 1, 5)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A7B4C.png', 61, 7, 4)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A9B5C.png', 64, 9, 5)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A2B9C.png', 65, 2, 9)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A9B4C.png', 66, 9, 4)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A0B4C.png', 68, 0, 4)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B4C.png', 69, 5, 4)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A2B8C.png', 70, 2, 8)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A9B8C.png', 71, 9, 8)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A3B4C.png', 73, 3, 4)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B0C.png', 74, 5, 0)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A6B0C.png', 75, 6, 0)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A7B9C.png', 77, 7, 9)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A9B2C.png', 78, 9, 2)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A7B2C.png', 79, 7, 2)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A1B9C.png', 80, 1, 9)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A6B6C.png', 81, 6, 6)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A6B9C.png', 82, 6, 9)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A1B6C.png', 83, 1, 6)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A6B7C.png', 85, 6, 7)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A3B0C.png', 87, 3, 0)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A4B2C.png', 90, 4, 2)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A1B2C.png', 91, 1, 2)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A1B7C.png', 93, 1, 7)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A9B3C.png', 98, 9, 3)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A8B7C.png', 100, 8, 7)")

con.execute("insert into set2 (filename, id, x, y) values ( 'A5B5D.png', 66, 9, 4)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B5D.png', 8, 9, 1)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B5D.png', 25, 0, 1)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B5D.png', 64, 9, 5)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B5D.png', 73, 3, 4)")

con.execute("insert into set2 (filename, id, x, y) values ( 'A5B5D.png', 90, 4, 2)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B5D.png', 29, 9, 0)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B5D.png', 60, 4, 4)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B5D.png', 22, 4, 9)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B5D.png', 92, 9, 9)")

con.execute("insert into set2 (filename, id, x, y) values ( 'A5B5D.png', 84, 0, 2)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B5D.png', 7, 2, 2)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B5D.png', 32, 5, 2)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B5D.png', 63, 8, 5)")
con.execute("insert into set2 (filename, id, x, y) values ( 'A5B5D.png', 44, 7, 5)")

con.execute("insert into set3 (filename, id, x, y) values ( 'A2B4C.png', 6, 2, 4)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A2B2C.png', 7, 2, 2)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A2B7C.png', 9, 2, 7)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B6C.png', 10, 5, 6)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A3B6C.png', 11, 3, 6)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A9B6C.png', 13, 9, 6)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A1B4C.png', 15, 1, 4)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A3B9C.png', 17, 3, 9)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A3B8C.png', 18, 3, 8)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A3B5C.png', 19, 3, 5)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A4B9C.png', 22, 4, 9)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A0B7C.png', 24, 0, 7)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A6B8C.png', 26, 6, 8)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A7B7C.png', 28, 7, 7)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A4B6C.png', 30, 4, 6)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B2C.png', 32, 5, 2)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A8B3C.png', 34, 8, 3)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A8B1C.png', 36, 8, 1)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A1B3C.png', 38, 1, 3)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A0B5C.png', 39, 0, 5)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A8B0C.png', 40, 8, 0)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A3B1C.png', 42, 3, 1)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A7B5C.png', 44, 7, 5)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A0B0C.png', 46, 0, 0)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A7B0C.png', 47, 7, 0)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A6B4C.png', 48, 6, 4)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A4B8C.png', 51, 4, 8)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A4B7C.png', 54, 4, 7)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A8B8C.png', 55, 8, 8)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A2B1C.png', 57, 2, 1)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A8B6C.png', 58, 8, 6)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A4B4C.png', 60, 4, 4)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A2B0C.png', 62, 2, 0)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A8B5C.png', 63, 8, 5)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B3C.png', 67, 5, 3)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A4B5C.png', 72, 4, 5)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B9C.png', 76, 5, 9)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A0B2C.png', 84, 0, 2)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A7B1C.png', 86, 7, 1)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A9B7C.png', 88, 9, 7)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A3B3C.png', 89, 3, 3)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A9B9C.png', 92, 9, 9)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A0B3C.png', 94, 0, 3)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A3B2C.png', 95, 3, 2)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A0B6C.png', 96, 0, 6)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B7C.png', 97, 5, 7)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A0B9C.png', 99, 0, 9)")

con.execute("insert into set3 (filename, id, x, y) values ( 'A5B5D.png', 90, 4, 2)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B5D.png', 29, 9, 0)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B5D.png', 60, 4, 4)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B5D.png', 22, 4, 9)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B5D.png', 92, 9, 9)")

con.execute("insert into set3 (filename, id, x, y) values ( 'A5B5D.png', 28, 7, 7)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B5D.png', 42, 3, 1)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B5D.png', 58, 8, 6)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B5D.png', 10, 5, 6)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B5D.png', 95, 3, 2)")

con.execute("insert into set3 (filename, id, x, y) values ( 'A5B5D.png', 84, 0, 2)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B5D.png', 7, 2, 2)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B5D.png', 32, 5, 2)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B5D.png', 63, 8, 5)")
con.execute("insert into set3 (filename, id, x, y) values ( 'A5B5D.png', 44, 7, 5)")


con.commit()

# close database
con.close()
